spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://192.168.20.162:5432/mydb2
    username: myuser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
